---

- hosts: all
  become: true
  tasks:

  - name: update repository
    dnf: 
      update_cache: yes

  - name: install httpd package
    dnf:
      name: httpd
      state: latest

  - name: install docker
    dnf:
      name: docker
      state: latest
