---

- hosts: all
  become: true
  tasks:

  - name: install httpd and docker package
    dnf:
      name:
        - httpd
        - docker
      state: latest
      update_cache: yes
    when: ansible_distribution == "Rocky"
